
- hosts: webservers

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes
      become: yes
    
    - name: copy html file
      ansible.builtin.copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
      notify:
        - restart nginx
      become: yes

    - name: copy config file
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes
    
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
