
- hosts: webservers

  tasks:
    - name: update cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      tags: update

    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
      become: yes
      tags: install

    - name: install Nodejs
      ansible.builtin.apt:
        name: nodejs
        state: latest
      become: yes
      tags: install

    - name: install make
      ansible.builtin.apt:
        name: make
        state: present
      become: yes
      tags: install

    - name: create user
      ansible.builtin.user:
        name: arya
        state: present
      become: yes
      tags: create