
- hosts: webservers
  vars:
    vars:
    users:
      - name: jaime
        email: jaime@test.com
      - name: sansa
        email: sansa@test.com
      - name: robert
        email: robert@test.com
  tasks:
  - name: create a group
    ansible.builtin.group:
        name: test
        state: present
    become: yes

  - name: add users
    ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        groups: test
    loop: "{{ users }}"
    become: yes
  
  - name: copy gitconfig file
    ansible.builtin.template:
        src: files/.gitconfig
        dest: "/home/{{ item.name }}/.gitconfig"
    loop: "{{ users }}"
    become: yes

  - name: add public ssh key
    ansible.posix.authorized_key:
        user: "{{item.name}}"
        state: present
        key: "{{ lookup('file', 'files/id_ed25519.pub') }}"
        path: "/home/{{ item.name }}/.ssh/authorized_keys"
        manage_dir: false
    loop: "{{users}}"
    become: yes
 